import {
  Customer,
  CustomerListResponse,
  ExplanationResponse,
  DriftApiResponse,
  DriftReport,
  ModelMetrics,
} from "./types";

export const MOCK_CUSTOMERS: Customer[] = [
  {
    customer_id: "CUST-0192",
    tenure_months: 4,
    contract_type: "Month-to-month",
    monthly_charges: 104.5,
    total_charges: 418.0,
    support_tickets: 7,
    last_login_days: 14,
    monthly_usage_gb: 42.0,
    payment_method: "Electronic check",
    paperless_billing: "Yes",
    online_security: "No",
    tech_support: "No",
    num_products: 1,
    churn_probability: 0.912,
    risk_tier: "HIGH",
    top_risk_driver: "High Support Escalations (7 tickets)",
    last_scored_at: "2026-09-06 18:45:10",
  },
  {
    customer_id: "CUST-0481",
    tenure_months: 2,
    contract_type: "Month-to-month",
    monthly_charges: 98.2,
    total_charges: 196.4,
    support_tickets: 6,
    last_login_days: 21,
    monthly_usage_gb: 28.5,
    payment_method: "Electronic check",
    paperless_billing: "Yes",
    online_security: "No",
    tech_support: "No",
    num_products: 1,
    churn_probability: 0.884,
    risk_tier: "HIGH",
    top_risk_driver: "Unresolved Technical Tickets & Inactivity",
    last_scored_at: "2026-09-06 18:42:04",
  },
  {
    customer_id: "CUST-0219",
    tenure_months: 6,
    contract_type: "Month-to-month",
    monthly_charges: 89.9,
    total_charges: 539.4,
    support_tickets: 5,
    last_login_days: 18,
    monthly_usage_gb: 55.0,
    payment_method: "Bank transfer",
    paperless_billing: "Yes",
    online_security: "No",
    tech_support: "No",
    num_products: 2,
    churn_probability: 0.841,
    risk_tier: "HIGH",
    top_risk_driver: "High Monthly Price on Month-to-Month Term",
    last_scored_at: "2026-09-06 18:39:15",
  },
  {
    customer_id: "CUST-0744",
    tenure_months: 8,
    contract_type: "Month-to-month",
    monthly_charges: 79.5,
    total_charges: 636.0,
    support_tickets: 4,
    last_login_days: 12,
    monthly_usage_gb: 64.0,
    payment_method: "Electronic check",
    paperless_billing: "No",
    online_security: "No",
    tech_support: "Yes",
    num_products: 2,
    churn_probability: 0.776,
    risk_tier: "HIGH",
    top_risk_driver: "Low Platform Engagement (Last login 12d ago)",
    last_scored_at: "2026-09-06 18:33:40",
  },
  {
    customer_id: "CUST-0305",
    tenure_months: 11,
    contract_type: "Month-to-month",
    monthly_charges: 75.0,
    total_charges: 825.0,
    support_tickets: 3,
    last_login_days: 9,
    monthly_usage_gb: 88.0,
    payment_method: "Credit card",
    paperless_billing: "Yes",
    online_security: "Yes",
    tech_support: "No",
    num_products: 2,
    churn_probability: 0.685,
    risk_tier: "HIGH",
    top_risk_driver: "Support Ticket Escalation Frequency",
    last_scored_at: "2026-09-06 18:28:10",
  },
  {
    customer_id: "CUST-0562",
    tenure_months: 15,
    contract_type: "Month-to-month",
    monthly_charges: 68.0,
    total_charges: 1020.0,
    support_tickets: 2,
    last_login_days: 8,
    monthly_usage_gb: 110.0,
    payment_method: "Credit card",
    paperless_billing: "Yes",
    online_security: "No",
    tech_support: "No",
    num_products: 2,
    churn_probability: 0.542,
    risk_tier: "MEDIUM",
    top_risk_driver: "Month-to-Month Contract Vulnerability",
    last_scored_at: "2026-09-06 18:15:22",
  },
  {
    customer_id: "CUST-0891",
    tenure_months: 18,
    contract_type: "Month-to-month",
    monthly_charges: 62.5,
    total_charges: 1125.0,
    support_tickets: 2,
    last_login_days: 6,
    monthly_usage_gb: 140.0,
    payment_method: "Bank transfer",
    paperless_billing: "No",
    online_security: "Yes",
    tech_support: "No",
    num_products: 3,
    churn_probability: 0.478,
    risk_tier: "MEDIUM",
    top_risk_driver: "Short Account Age (18 months)",
    last_scored_at: "2026-09-06 18:02:18",
  },
  {
    customer_id: "CUST-0128",
    tenure_months: 22,
    contract_type: "One year",
    monthly_charges: 84.0,
    total_charges: 1848.0,
    support_tickets: 3,
    last_login_days: 7,
    monthly_usage_gb: 125.0,
    payment_method: "Credit card",
    paperless_billing: "Yes",
    online_security: "Yes",
    tech_support: "Yes",
    num_products: 3,
    churn_probability: 0.385,
    risk_tier: "MEDIUM",
    top_risk_driver: "Upcoming Annual Contract Expiry Window",
    last_scored_at: "2026-09-06 17:55:09",
  },
  {
    customer_id: "CUST-0402",
    tenure_months: 36,
    contract_type: "One year",
    monthly_charges: 55.0,
    total_charges: 1980.0,
    support_tickets: 1,
    last_login_days: 3,
    monthly_usage_gb: 210.0,
    payment_method: "Bank transfer",
    paperless_billing: "Yes",
    online_security: "Yes",
    tech_support: "Yes",
    num_products: 3,
    churn_probability: 0.182,
    risk_tier: "LOW",
    top_risk_driver: "Steady Usage Retention Anchor",
    last_scored_at: "2026-09-06 17:40:02",
  },
  {
    customer_id: "CUST-0610",
    tenure_months: 48,
    contract_type: "Two year",
    monthly_charges: 45.0,
    total_charges: 2160.0,
    support_tickets: 0,
    last_login_days: 1,
    monthly_usage_gb: 320.0,
    payment_method: "Credit card",
    paperless_billing: "No",
    online_security: "Yes",
    tech_support: "Yes",
    num_products: 4,
    churn_probability: 0.048,
    risk_tier: "LOW",
    top_risk_driver: "Long-term Multi-Year Contract Loyalty",
    last_scored_at: "2026-09-06 17:25:44",
  },
  {
    customer_id: "CUST-0925",
    tenure_months: 60,
    contract_type: "Two year",
    monthly_charges: 42.0,
    total_charges: 2520.0,
    support_tickets: 0,
    last_login_days: 1,
    monthly_usage_gb: 410.0,
    payment_method: "Credit card",
    paperless_billing: "No",
    online_security: "Yes",
    tech_support: "Yes",
    num_products: 4,
    churn_probability: 0.024,
    risk_tier: "LOW",
    top_risk_driver: "Enterprise Account Tenure (60 months)",
    last_scored_at: "2026-09-06 17:10:19",
  },
];

export const MOCK_SUMMARY = {
  total_customers: 503,
  avg_churn_probability: 0.245,
  high_risk_count: 80,
  high_risk_pct: 15.9,
  total_monthly_revenue_monitored: 38420.0,
};

export const MOCK_DRIFT_REPORT: DriftApiResponse = {
  latest_report: {
    timestamp: "2026-09-06T18:45:00Z",
    overall_status: "STABLE",
    dataset_drift_detected: false,
    drifted_features_count: 0,
    critical_features_count: 0,
    total_features_evaluated: 6,
    max_psi: 0.051,
    mean_psi: 0.034,
    current_batch_size: 503,
    features: [
      {
        feature: "support_tickets",
        type: "numerical",
        test_used: "Kolmogorov-Smirnov & PSI",
        ks_statistic: 0.058,
        p_value: 0.214,
        psi: 0.042,
        status: "STABLE",
        is_drifted: false,
        baseline_mean: 1.84,
        current_mean: 1.91,
        mean_shift_pct: 3.8,
      },
      {
        feature: "monthly_charges",
        type: "numerical",
        test_used: "Kolmogorov-Smirnov & PSI",
        ks_statistic: 0.038,
        p_value: 0.651,
        psi: 0.028,
        status: "STABLE",
        is_drifted: false,
        baseline_mean: 64.76,
        current_mean: 65.12,
        mean_shift_pct: 0.55,
      },
      {
        feature: "tenure_months",
        type: "numerical",
        test_used: "Kolmogorov-Smirnov & PSI",
        ks_statistic: 0.045,
        p_value: 0.482,
        psi: 0.035,
        status: "STABLE",
        is_drifted: false,
        baseline_mean: 32.4,
        current_mean: 31.9,
        mean_shift_pct: -1.5,
      },
      {
        feature: "last_login_days",
        type: "numerical",
        test_used: "Kolmogorov-Smirnov & PSI",
        ks_statistic: 0.062,
        p_value: 0.178,
        psi: 0.051,
        status: "STABLE",
        is_drifted: false,
        baseline_mean: 4.8,
        current_mean: 5.3,
        mean_shift_pct: 10.4,
      },
      {
        feature: "monthly_usage_gb",
        type: "numerical",
        test_used: "Kolmogorov-Smirnov & PSI",
        ks_statistic: 0.041,
        p_value: 0.59,
        psi: 0.031,
        status: "STABLE",
        is_drifted: false,
        baseline_mean: 182.5,
        current_mean: 179.8,
        mean_shift_pct: -1.48,
      },
      {
        feature: "contract_type",
        type: "categorical",
        test_used: "Categorical PSI",
        ks_statistic: null,
        p_value: null,
        psi: 0.019,
        status: "STABLE",
        is_drifted: false,
      },
    ],
  },
  drift_history_timeline: [
    {
      id: 1,
      timestamp: "2026-09-06 12:00:00",
      overall_status: "STABLE",
      drifted_features_count: 0,
      critical_features_count: 0,
      max_psi: 0.041,
      mean_psi: 0.028,
    },
    {
      id: 2,
      timestamp: "2026-09-06 18:45:00",
      overall_status: "STABLE",
      drifted_features_count: 0,
      critical_features_count: 0,
      max_psi: 0.051,
      mean_psi: 0.034,
    },
  ],
};

export const MOCK_METRICS: ModelMetrics = {
  accuracy: 0.8313,
  precision: 0.596,
  recall: 0.5488,
  f1: 0.5714,
  roc_auc: 0.8656,
  pr_auc: 0.6335,
  confusion_matrix: {
    true_negative: 583,
    false_positive: 62,
    false_negative: 73,
    true_positive: 82,
  },
  best_hyperparameters: {
    max_depth: 4,
    learning_rate: 0.05,
    n_estimators: 150,
    subsample: 0.8,
    colsample_bytree: 0.8,
  },
  feature_importances: [
    { feature: "Contract: Month-to-Month", importance: 0.285 },
    { feature: "Tenure (Months)", importance: 0.214 },
    { feature: "Support Tickets", importance: 0.182 },
    { feature: "Monthly Charges ($)", importance: 0.129 },
    { feature: "Days Since Last Login", importance: 0.098 },
    { feature: "Online Security: None", importance: 0.052 },
    { feature: "Tech Support: None", importance: 0.04 },
  ],
};

export function getMockExplanation(customerId: string): ExplanationResponse {
  const cust = MOCK_CUSTOMERS.find((c) => c.customer_id === customerId) || MOCK_CUSTOMERS[0];
  const isHigh = cust.churn_probability >= 0.65;
  const isMed = cust.churn_probability >= 0.35 && cust.churn_probability < 0.65;

  return {
    customer_id: cust.customer_id,
    churn_probability: cust.churn_probability,
    risk_tier: cust.risk_tier,
    predicted_churn: isHigh ? 1 : 0,
    base_value: -1.34,
    explanation_summary: isHigh
      ? `Customer ${cust.customer_id} exhibits critical risk driven primarily by high support ticket escalations (${cust.support_tickets} tickets) and lack of long-term contract commitment.`
      : isMed
      ? `Customer ${cust.customer_id} displays moderate volatility with a short tenure (${cust.tenure_months} mo) balanced by active feature usage.`
      : `Customer ${cust.customer_id} is well-anchored with long tenure (${cust.tenure_months} mo) and proactive service add-ons.`,
    top_risk_drivers: isHigh
      ? [
          {
            feature: "support_tickets",
            display_name: "Support Tickets",
            shap_value: 0.48,
            original_value: cust.support_tickets,
            direction: "risk_increase",
          },
          {
            feature: "contract_type",
            display_name: "Contract Type",
            shap_value: 0.35,
            original_value: cust.contract_type,
            direction: "risk_increase",
          },
          {
            feature: "last_login_days",
            display_name: "Days Since Last Login",
            shap_value: 0.22,
            original_value: cust.last_login_days,
            direction: "risk_increase",
          },
        ]
      : [
          {
            feature: "monthly_charges",
            display_name: "Monthly Charges",
            shap_value: 0.08,
            original_value: cust.monthly_charges,
            direction: "risk_increase",
          },
        ],
    top_retention_anchors: isHigh
      ? [
          {
            feature: "monthly_usage_gb",
            display_name: "Monthly Usage (GB)",
            shap_value: -0.09,
            original_value: cust.monthly_usage_gb,
            direction: "retention_anchor",
          },
        ]
      : [
          {
            feature: "tenure_months",
            display_name: "Tenure Months",
            shap_value: -0.62,
            original_value: cust.tenure_months,
            direction: "retention_anchor",
          },
          {
            feature: "contract_type",
            display_name: "Contract Commitment",
            shap_value: -0.44,
            original_value: cust.contract_type,
            direction: "retention_anchor",
          },
        ],
    all_contributions: [
      {
        feature: "support_tickets",
        display_name: "Support Tickets",
        shap_value: isHigh ? 0.48 : -0.15,
        original_value: cust.support_tickets,
        direction: isHigh ? "risk_increase" : "retention_anchor",
      },
      {
        feature: "contract_type",
        display_name: "Contract Type",
        shap_value: isHigh ? 0.35 : -0.44,
        original_value: cust.contract_type,
        direction: isHigh ? "risk_increase" : "retention_anchor",
      },
      {
        feature: "tenure_months",
        display_name: "Tenure Months",
        shap_value: isHigh ? 0.12 : -0.62,
        original_value: cust.tenure_months,
        direction: isHigh ? "risk_increase" : "retention_anchor",
      },
      {
        feature: "monthly_charges",
        display_name: "Monthly Charges",
        shap_value: 0.08,
        original_value: cust.monthly_charges,
        direction: "risk_increase",
      },
    ],
    retention_playbook: isHigh
      ? {
          title: "Senior Success Engineer Escalation & Retention Call",
          urgency: "Immediate (Within 24h)",
          category: "Technical Support Resolution",
          action: `Assign dedicated support lead to resolve all outstanding support tickets (${cust.support_tickets} logged). Offer 2 months of free Tech Support add-on and a 15% discount for a 1-year annual lock-in.`,
          projected_impact: "Projected 38% reduction in 30-day churn probability.",
        }
      : {
          title: "Account Health Check & Contract Renewal Incentive",
          urgency: "Standard (Next 14 Days)",
          category: "Relationship Building",
          action: "Schedule quarterly executive review and propose renewal discount on multi-year contract.",
          projected_impact: "Sustains 95%+ account retention probability.",
        },
  };
}
